apiVersion: v1
kind: Service
metadata:
  name: influx
  namespace: nexclipper
spec:
  ports:
  - name: "8083"
    port: 8084
    targetPort: 8083
  - name: "8086"
    port: 8087
    targetPort: 8086
  selector:
    app: influx
  type: NodePort
