kind: Deployment
apiVersion: extensions/v1beta1
metadata:
 name: nexclipperlight
spec:
 replicas: 1
 selector:
   matchLabels:
     component: nexclipperlight
 template:
   metadata:
     labels:
       component: nexclipperlight
   spec:
     containers:
       - name: nexclipperlight
         image: nexclipper/nexclipper
         ports:
           - containerPort: 9001
         resources:
           requests:
             cpu: 100m
         volumeMounts:
         - mountPath: /var/run/docker.sock
           name: dockersocket
         - mountPath: /var/lib/docker
           name: docker
     volumes:
     - name: dockersocket
       hostPath:
           path: /var/run/docker.sock
           type: "Socket"
     - name: docker
       hostPath:
           path: /var/lib/docker
---
kind: Service
apiVersion: v1
metadata:
 name: nexclipperlight
spec:
 type: LoadBalancer
 ports:
   - port: 10001
     targetPort: 9001
 selector:
   component: nexclipperlight
