apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: nexclipper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: solsson/kafka-manager@sha256:da602758fd542139284d1d106e7dfed78898e0f1eb9756597ab9aee8cfccd763
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zk-svc.default:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: nexclipper
spec:
  selector:
    app: kafka-manager
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
