---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-kafka-0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: kafka0
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-kafka-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: kafka1
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-kafka-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: kafka2
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-zk-0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: zk0
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-zk-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: zk1
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-zk-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: zk2
  resources:
    requests:
      storage: 10Gi
---
